server:
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

    context-path: /

  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm_db
    hikari:
      username: root
      password: hsp

  security:
    user:
      name: user
      password: 111
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

  type-aliases-package: com.weikai.pojo
